---
name: haskell-library-template
version: 1.0.4.0
maintainer: Freckle Education
category: Utils
github: freckle/haskell-library-template
synopsis: [synopsis]
description: Please see README.md

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - package.yaml

dependencies:
  - base < 5

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:

tests:
  spec:
    main: Main.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N"
    dependencies:
      - freckle-app
      - hspec

  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - freckle-app
