resolver: lts-19.6

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-unsafe
  - -Wno-safe
